=== romsom/synthed/instruments/data.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    data.dtd

    This data definition schema is designed to describe a 
    MIDI device dump and its parameters. 
    
    Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.
    
    This program is free software; you can redistribute it and/or modify it 
    under the terms of the GNU General Public License as published by the 
    Free Software Foundation; either version 2 of the License, or (at your 
    option) any later version.
    
    This program is distributed in the hope that it will be useful, but 
    WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
    General Public License for more details.
    
    You should have received a copy of the GNU General Public License 
    along with this program; if not, write to the Free Software Foundation, 
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT data (patch)*>
    
<!ELEMENT patch (parameter)*>
<!ATTLIST patch
    id ID #REQUIRED
    caption CDATA #IMPLIED
    length CDATA #IMPLIED
    type CDATA #IMPLIED>
    
<!ELEMENT parameter (byte|array)*>
<!ATTLIST parameter
    id ID #REQUIRED
    alt CDATA #IMPLIED
    type CDATA #IMPLIED
    pad CDATA #IMPLIED
    init CDATA #IMPLIED
    min CDATA #IMPLIED
    max CDATA #IMPLIED
    validate CDATA #IMPLIED>

<!ELEMENT byte EMPTY>
<!ATTLIST byte
    offset CDATA #REQUIRED 
    bitstart CDATA #IMPLIED
    bitstop CDATA #IMPLIED>

<!ELEMENT array EMPTY>
<!ATTLIST array
    offset CDATA #REQUIRED 
    length CDATA #REQUIRED>

=== romsom/synthed/instruments/access/virus_c/virus_c_midi.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	virus_c_midi.xml

	This data definition should be compatible with Access Virus C.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE data SYSTEM "../../data.dtd">

<data>

  <!-- Make a default editor to edit and print patches -->
  <!-- Make a utility to send and receive these -->

  <!-- Bank Select -->

  <!-- Program Change -->

  <!-- Part Bank Select -->

  <!-- Part Bank Change -->

  <!-- Part Program Change -->
  <patch id="part_program_change" caption="Part Program Change" type="message">
    <parameter value="0xF000203301">
      <array offset="0" length="5"/>
    </parameter>
    <parameter id="PPC_device_id">
      <byte offset="5"/>
    </parameter>
    <parameter value="0x72">
      <byte offset="6"/>
    </parameter>
    <parameter id="PPC_part_number" min="0" max="15">
      <byte offset="7"/>
    </parameter>
    <parameter value="0x21">
      <byte offset="8"/>
    </parameter>
    <parameter id="PPC_program_number" min="0" max="127">
      <byte offset="9"/>
    </parameter>
    <parameter value="0xF7">
      <array offset="10" length="1"/>
    </parameter>
  </patch>

  <!-- Multi Program Change -->

  <!-- Parameter value change -->
  <patch id="sysex_parameter_change" caption="Sysex Parameter Change" type="message">
    <parameter value="0xF000203301">
      <array offset="0" length="5"/>
    </parameter>
    <parameter id="SPC_device_id">
      <byte offset="5"/>
    </parameter>
    <parameter value="7">
      <byte offset="6" bitstart="4" bitstop="7"/>
    </parameter>
    <parameter id="SPC_page_number" min="0" max="3">
      <byte offset="6" bitstart="0" bitstop="3"/>
    </parameter>
    <parameter id="SPC_part_number" min="0" max="15">
      <byte offset="7"/>
    </parameter>
    <parameter id="SPC_parameter_number" min="0" max="127">
      <byte offset="8"/>
    </parameter>
    <parameter id="SPC_parameter_value" min="0" max="127">
      <byte offset="9"/>
    </parameter>
    <parameter value="0xF7">
      <array offset="10" length="1"/>
    </parameter>
  </patch>

  <!-- Single program dump -->
  <patch id="single_dump" caption="Single Dump" type="message">
    <parameter value="0xF000203301">
      <array offset="0" length="5"/>
    </parameter>
    <parameter id="SD_device_id">
      <byte offset="5"/>
    </parameter>
    <parameter id="SD_command" value="0x10">
      <array offset="6" length="1"/>
    </parameter>
    <parameter id="SD_bank_number">
      <byte offset="7"/>
    </parameter>
    <parameter id="SD_program_number">
      <byte offset="8"/>
    </parameter>
    <parameter id="SD_patch">
      <array offset="9" length="256"/>
    </parameter>
    <parameter id="SD_checksum">
      <byte offset="265"/>
    </parameter>
    <parameter value="0xF7">
      <array offset="266" length="1"/>
    </parameter>
  </patch>

  <!-- Request a single program dump -->
  <patch id="single_request" caption="Single Request" type="message">
    <parameter value="0xF000203301">
      <array offset="0" length="5"/>
    </parameter>
    <parameter id="SR_device_id">
      <byte offset="5"/>
    </parameter>
    <parameter id="SR_command" value="0x30">
      <array offset="6" length="1"/>
    </parameter>
    <parameter id="SR_bank_number">
      <byte offset="7"/>
    </parameter>
    <parameter id="SR_program_number">
      <byte offset="8"/>
    </parameter>
    <parameter value="0xF7">
      <array offset="9" length="1"/>
    </parameter>
  </patch>

</data>

=== romsom/synthed/instruments/korg/triton/triton_midi.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	triton_midi.xml

	This data definition should be compatible with Korg TRITON, pro, 
	proX, Rack and Studio. Korg TRITON LE and KARMA differ slightly, so they 
	can be derived from this definition at a later time.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE data SYSTEM "../../data.dtd">

<data>

<!-- Make a default editor to edit and print patches -->
<!-- Make a utility to send and receive these -->
<patch id="mode_request" caption="Mode Request">
	<parameter value="0xF042">
		<array offset="0" length="2"/>
	</parameter>
	<parameter value="0x03">
		<byte offset="2" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="MR_global_channel" min="0" max="15">
		<byte offset="2" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter value="0x5012F7">
		<array offset="3" length="3"/>
	</parameter>
</patch>

<patch id="current_pgm_param_dump_request" caption="Current Program Parameter Dump Request">
	<parameter value="0xF042">
		<array offset="0" length="2"/>
	</parameter>
	<parameter value="0x03">
		<byte offset="2" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="CPPDR_global_channel" min="0" max="15">
		<byte offset="2" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter value="0x501000F7">
		<array offset="3" length="4"/>
	</parameter>
</patch>

<patch id="pgm_param_dump_request" caption="Program Parameter Dump Request">
	<parameter value="0xF042">
		<array offset="0" length="2"/>
	</parameter>
	<parameter value="0x03">
		<byte offset="2" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="PPDR_global_channel" min="0" max="15">
		<byte offset="2" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter value="0x501C">
		<array offset="3" length="2"/>
	</parameter>
	<parameter id="PPDR_kind" min="0" max="15">
		<byte offset="5" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="PDDR_bank" min="0" max="15">
		<byte offset="5" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter id="PDDR_program" min="0" max="127">
		<byte offset="6"/>
	</parameter>
	<parameter value="0xF7">
		<byte offset="7"/>
	</parameter>
</patch>

<patch id="pgm_param_dump" caption="Program Parameter Dump">
	<parameter value="0xF042">
		<array offset="0" length="2"/>
	</parameter>
	<parameter value="0x03">
		<byte offset="2" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="PPD_global_channel" min="0" max="15">
		<byte offset="2" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter value="0x504C">
		<array offset="3" length="2"/>
	</parameter>
	<parameter id="PPD_kind" min="0" max="15">
		<byte offset="5" bitstart="4" bitstop="7"/>
	</parameter>
	<parameter id="PPD_bank" min="0" max="15">
		<byte offset="5" bitstart="0" bitstop="3"/>
	</parameter>
	<parameter id="PPD_program" min="0" max="127">
		<byte offset="6"/>
	</parameter>
	<parameter id="PPD_data">
		<!-- Note this is variable length delimited by a 0xF7 -->
		<array offset="7" enddelimiter="0xF7"/>
	</parameter>
	<parameter value="0xF7">
		<byte begindelimiter="0xF7"/>
	</parameter>
</patch>

</data>
