=== romsom/synthed/instruments/decoder.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    decoder.dtd

    This decoder schema is designed to describe and 
    facilitate editing of MIDI synthesizer sysex parameters.
    
    Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.
    
    This program is free software; you can redistribute it and/or modify it 
    under the terms of the GNU General Public License as published by the 
    Free Software Foundation; either version 2 of the License, or (at your 
    option) any later version.
    
    This program is distributed in the hope that it will be useful, but 
    WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
    General Public License for more details.
    
    You should have received a copy of the GNU General Public License 
    along with this program; if not, write to the Free Software Foundation, 
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT decoder (lists,scales)>
<!ATTLIST decoder
    id ID #IMPLIED
    caption CDATA #IMPLIED>

<!ELEMENT lists (list*)>
<!ATTLIST lists
    id ID #IMPLIED>

<!ELEMENT list (item|list)*>
<!ATTLIST list
    id ID #IMPLIED>
    
<!ELEMENT item EMPTY>
<!ATTLIST item
    value CDATA #REQUIRED>
    
<!ELEMENT scales (scale*)>
<!ATTLIST scales
    id ID #IMPLIED>

<!ELEMENT scale (range+)>
<!ATTLIST scale
    id ID #REQUIRED
    min CDATA #REQUIRED
    max CDATA #REQUIRED
    format CDATA #IMPLIED
    unit CDATA #IMPLIED>
    
<!ELEMENT range EMPTY>
<!ATTLIST range
    min CDATA #REQUIRED
    max CDATA #REQUIRED
    minval CDATA #REQUIRED
    increment CDATA #IMPLIED
    format CDATA #IMPLIED
    unit CDATA #IMPLIED
    multiplier CDATA #IMPLIED>

=== romsom/synthed/instruments/kurzweil/k2000/k2000_decoder.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	k2000_decoder.xml

	This data definition should be compatible with the Kurzweil K2000, 
	K2500 and K2600 series.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE decoder SYSTEM "../../decoder.dtd">

<decoder>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Lists of values that can be referenced by controls. They are arranged 
	alphabetically in the hope that they will be easier to maintain. 
	Lists may be nested. 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<lists>

<!-- AMPENV modes -->
<list id="list_ampenv_modes">
	<item value="Natural"/>
	<item value="User"/>
</list>

<!-- AMPENV loop types -->
<list id="list_ampenv_loop_types">
	<item value="Off"/>
	<item value="Seg1F"/>
	<item value="Seg2F"/>
	<item value="Seg3F"/>
	<item value="Seg1B"/>
	<item value="Seg2B"/>
	<item value="Seg3B"/>
</list>

<!-- ASR modes -->
<list id="list_asr_modes">
	<item value="Norm"/>
	<item value="Hold"/>
	<item value="Rept"/>
</list>

<!-- Control sources -->
<list id="list_control_sources">
	<item value="OFF"/>
	<item value="MWheel"/>
	<item value="Breath"/>
	<item value="MIDI03"/>
	<item value="Foot"/>
	<item value="PortTim"/>
	<item value="Data"/>
	<item value="Volume"/>
	<item value="Balance"/>
	<item value="MIDI09"/>
	<item value="Pan"/>
	<item value="Express"/>
	<item value="MIDI12"/>
	<item value="MIDI13"/>
	<item value="MIDI14"/>
	<item value="MIDI15 (AuxBend2)"/>
	<item value="Ctl A"/>
	<item value="Ctl B"/>
	<item value="Ctl C"/>
	<item value="Ctl D"/>
	<item value="MIDI20"/>
	<item value="MIDI21 (AuxBend1)"/>
	<item value="MIDI22"/>
	<item value="MIDI23"/>
	<item value="MIDI24"/>
	<item value="MIDI25"/>
	<item value="MIDI26"/>
	<item value="MIDI27"/>
	<item value="MIDI28"/>
	<item value="MIDI29"/>
	<item value="MIDI30"/>
	<item value="MIDI31"/>
	<item value="Chan St"/>
	<item value="MPress"/>
	<item value="BMPress"/>
	<item value="PWheel"/>
	<item value="Bi-Mwl"/>
	<item value="AbsPwl"/>
	<item value="GASR2"/>
	<item value="GFUN2"/>
	<item value="GLFO2"/>
	<item value="GLFO2ph"/>
	<item value="GFUN4"/>
	<item value="VolCtl"/>
	<item value="BalCtl"/>
	<item value="PanCtl"/>
	<item value="ChanCnt"/>
	<item value="A Clk4"/>
	<item value="~AClk4"/>
	<item value="B Clk4"/>
	<item value="-BClk4"/>
	<item value="A Clk2"/>
	<item value="~AClk2"/>
	<item value="B Clk2"/>
	<item value="-BClk2"/>
	<item value="Tempo/SyncSt"/>
	<item value="AClock"/>
	<item value="~A Clk"/>
	<item value="BClock"/>
	<item value="~B Clk"/>
	<item value="GPhase1"/>
	<item value="GPhase2"/>
	<item value="GRandV1"/>
	<item value="GRandV2"/>
	<item value="Sustain"/>
	<item value="PortSw"/>
	<item value="SostPd"/>
	<item value="SoftPd"/>
	<item value="LegatoSw"/>
	<item value="FrezPd"/>
	<item value="MIDI70"/>
	<item value="MIDI71"/>
	<item value="MIDI72"/>
	<item value="MIDI73"/>
	<item value="MIDI74"/>
	<item value="MIDI75"/>
	<item value="MIDI76"/>
	<item value="MIDI77"/>
	<item value="MIDI78"/>
	<item value="MIDI79"/>
	<item value="Ctl E"/>
	<item value="Ctl F"/>
	<item value="Ctl G"/>
	<item value="Ctl H"/>
	<item value="MIDI84"/>
	<item value="MIDI85"/>
	<item value="MIDI86"/>
	<item value="MIDI87"/>
	<item value="MIDI88"/>
	<item value="MIDI89"/>
	<item value="MIDI90"/>
	<item value="FX Depth"/>
	<item value="MIDI92"/>
	<item value="MIDI93"/>
	<item value="MIDI94"/>
	<item value="MIDI95"/>
	<item value="Note St"/>
	<item value="Key St"/>
	<item value="KeyNum"/>
	<item value="BKeyNum"/>
	<item value="AttVel"/>
	<item value="InvAVel"/>
	<item value="PPress"/>
	<item value="BPPress"/>
	<item value="RelVel"/>
	<item value="Bi-AVel"/>
	<item value="VTRIG1"/>
	<item value="VTRIG2"/>
	<item value="RandV1"/>
	<item value="RandV2"/>
	<item value="ASR1"/>
	<item value="ASR2"/>
	<item value="FUN1"/>
	<item value="FUN2"/>
	<item value="LFO1"/>
	<item value="LFO1ph"/>
	<item value="LFO2"/>
	<item value="LFO2ph"/>
	<item value="FUN3"/>
	<item value="FUN4"/>
	<item value="AMPENV"/>
	<item value="ENV2"/>
	<item value="ENV3"/>
	<item value="Loop St"/>
	<item value="PB Rate"/>
	<item value="Atk Stat"/>
	<item value="Rel Stat"/>
	<item value="ON"/>
	<item value="-ON"/>
	<item value="GKeyNum"/>
	<item value="GAttVel"/>
	<item value="GLowKey"/>
	<item value="GHiKey"/>
</list>

<!-- Function arguments = all control sources + constants -->
<list id="list_function_arguments">
	<item value="OFF"/>
	<item value="MWheel"/>
	<item value="Breath"/>
	<item value="MIDI03"/>
	<item value="Foot"/>
	<item value="PortTim"/>
	<item value="Data"/>
	<item value="Volume"/>
	<item value="Balance"/>
	<item value="MIDI09"/>
	<item value="Pan"/>
	<item value="Express"/>
	<item value="MIDI12"/>
	<item value="MIDI13"/>
	<item value="MIDI14"/>
	<item value="MIDI15 (AuxBend2)"/>
	<item value="Ctl A"/>
	<item value="Ctl B"/>
	<item value="Ctl C"/>
	<item value="Ctl D"/>
	<item value="MIDI20 (AuxBend1)"/>
	<item value="MIDI21"/>
	<item value="MIDI22"/>
	<item value="MIDI23"/>
	<item value="MIDI24"/>
	<item value="MIDI25"/>
	<item value="MIDI26"/>
	<item value="MIDI27"/>
	<item value="MIDI28"/>
	<item value="MIDI29"/>
	<item value="MIDI30"/>
	<item value="MIDI31"/>
	<item value="Chan St"/>
	<item value="MPress"/>
	<item value="BMPress"/>
	<item value="PWheel"/>
	<item value="Mwl"/>
	<item value="AbsPwl"/>
	<item value="GASR2"/>
	<item value="GFUN2"/>
	<item value="GLFO2"/>
	<item value="GLFO2ph"/>
	<item value="GFUN4"/>
	<item value="VolCtl"/>
	<item value="BalCtl"/>
	<item value="PanCtl"/>
	<item value="ChanCnt"/>
	<item value="A Clk4"/>
	<item value="~AClk4"/>
	<item value="Clk4"/>
	<item value="BClk4"/>
	<item value="Clk2"/>
	<item value="AClk2"/>
	<item value="Clk2"/>
	<item value="BClk2"/>
	<item value="Sync St / Tempo"/>
	<item value="AClock"/>
	<item value="Clk"/>
	<item value="BClock"/>
	<item value="Clk"/>
	<item value="GPhas1"/>
	<item value="GPhas2"/>
	<item value="GRand1"/>
	<item value="GRand2"/>
	<item value="Sustain"/>
	<item value="PortSw"/>
	<item value="SostPd"/>
	<item value="SoftPd"/>
	<item value="LegatoSw"/>
	<item value="FrezPd"/>
	<item value="MIDI70"/>
	<item value="MIDI71"/>
	<item value="MIDI72"/>
	<item value="MIDI73"/>
	<item value="MIDI74"/>
	<item value="MIDI75"/>
	<item value="MIDI76"/>
	<item value="MIDI77"/>
	<item value="MIDI78"/>
	<item value="MIDI79"/>
	<item value="Ctl E"/>
	<item value="Ctl F"/>
	<item value="Ctl G"/>
	<item value="Ctl H"/>
	<item value="MIDI84"/>
	<item value="MIDI85"/>
	<item value="MIDI86"/>
	<item value="MIDI87"/>
	<item value="MIDI88"/>
	<item value="MIDI89"/>
	<item value="MIDI90"/>
	<item value="FX Depth"/>
	<item value="MIDI92"/>
	<item value="MIDI93"/>
	<item value="MIDI94"/>
	<item value="MIDI95"/>
	<item value="Note St"/>
	<item value="Key St"/>
	<item value="KeyNum"/>
	<item value="BKeyNum"/>
	<item value="AttVel"/>
	<item value="InvAVel"/>
	<item value="PPress"/>
	<item value="BPPress"/>
	<item value="RelVel"/>
	<item value="AVel"/>
	<item value="VTRIG1"/>
	<item value="VTRIG2"/>
	<item value="RandV1"/>
	<item value="RandV2"/>
	<item value="ASR1"/>
	<item value="ASR2"/>
	<item value="FUN1"/>
	<item value="FUN2"/>
	<item value="LFO1"/>
	<item value="LFO1ph"/>
	<item value="LFO2"/>
	<item value="LFO2ph"/>
	<item value="FUN3"/>
	<item value="FUN4"/>
	<item value="AMPENV"/>
	<item value="ENV2"/>
	<item value="ENV3"/>
	<item value="Loop St"/>
	<item value="PB Rate"/>
	<item value="Atk Stat"/>
	<item value="Rel Stat"/>
	<item value="ON"/>
	<item value="ON"/>
	<item value="GKeyNum"/>
	<item value="GAttVel"/>
	<item value="GLowKey"/>
	<item value="GHiKey"/>
	<item value="-0.99"/>
	<item value="-0.98"/>
	<item value="-0.97"/>
	<item value="-0.96"/>
	<item value="-0.95"/>
	<item value="-0.94"/>
	<item value="-0.93"/>
	<item value="-0.92"/>
	<item value="-0.91"/>
	<item value="-0.90"/>
	<item value="-0.88"/>
	<item value="-0.86"/>
	<item value="-0.84"/>
	<item value="-0.82"/>
	<item value="-0.80"/>
	<item value="-0.78"/>
	<item value="-0.76"/>
	<item value="-0.74"/>
	<item value="-0.72"/>
	<item value="-0.70"/>
	<item value="-0.68"/>
	<item value="-0.66"/>
	<item value="-0.64"/>
	<item value="-0.62"/>
	<item value="-0.60"/>
	<item value="-0.58"/>
	<item value="-0.56"/>
	<item value="-0.54"/>
	<item value="-0.52"/>
	<item value="-0.50"/>
	<item value="-0.48"/>
	<item value="-0.46"/>
	<item value="-0.44"/>
	<item value="-0.42"/>
	<item value="-0.40"/>
	<item value="-0.38"/>
	<item value="-0.36"/>
	<item value="-0.34"/>
	<item value="-0.32"/>
	<item value="-0.30"/>
	<item value="-0.28"/>
	<item value="-0.26"/>
	<item value="-0.24"/>
	<item value="-0.22"/>
	<item value="-0.20"/>
	<item value="-0.18"/>
	<item value="-0.16"/>
	<item value="-0.14"/>
	<item value="-0.12"/>
	<item value="-0.10"/>
	<item value="-0.09"/>
	<item value="-0.08"/>
	<item value="-0.07"/>
	<item value="-0.06"/>
	<item value="-0.05"/>
	<item value="-0.04"/>
	<item value="-0.03"/>
	<item value="-0.02"/>
	<item value="-0.01"/>
	<item value="0.00"/>
	<item value="0.01"/>
	<item value="0.02"/>
	<item value="0.03"/>
	<item value="0.04"/>
	<item value="0.05"/>
	<item value="0.06"/>
	<item value="0.07"/>
	<item value="0.08"/>
