=== romsom/synthed/instruments/instrument.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    instrument.dtd

    This instrument definition schema is designed to describe and 
    facilitate editing of MIDI synthesizer sysex parameters.
    
    Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.
    
    This program is free software; you can redistribute it and/or modify it 
    under the terms of the GNU General Public License as published by the 
    Free Software Foundation; either version 2 of the License, or (at your 
    option) any later version.
    
    This program is distributed in the hope that it will be useful, but 
    WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
    General Public License for more details.
    
    You should have received a copy of the GNU General Public License 
    along with this program; if not, write to the Free Software Foundation, 
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT instrument (module,data,decoders,interfaces,modes)>
<!ATTLIST instrument
    id ID #REQUIRED>

<!ELEMENT module EMPTY>
<!ATTLIST module
	id CDATA #REQUIRED>

<!ELEMENT data (patch*)>

<!ELEMENT patch EMPTY>
<!ATTLIST patch
	path CDATA #REQUIRED>

<!ELEMENT decoders (decoder*)>

<!ELEMENT decoder EMPTY>
<!ATTLIST decoder
	path CDATA #REQUIRED>

<!ELEMENT interfaces (interface*)>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
	path CDATA #REQUIRED>

<!ELEMENT modes (mode*)>

<!ELEMENT mode (bank*)>
<!ATTLIST mode
    id ID #IMPLIED
    caption CDATA #IMPLIED>
    
<!ELEMENT bank EMPTY>
<!ATTLIST bank
	caption CDATA #REQUIRED
    min CDATA #REQUIRED
    max CDATA #REQUIRED>

=== romsom/synthed/instruments/korg/triton/triton_rack.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	triton_rack.xml

	This instrument definition should be compatible with Korg TRITON, pro, 
	proX, Rack and Studio. Korg TRITON LE and KARMA differ slightly, so they 
	can be derived from this definition at a later time.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE instrument SYSTEM "../../instrument.dtd">

<instrument id="triton_rack">

	<module id="triton"/>
	
	<data>
		<patch path="triton_pcm.xml"/>
		<patch path="triton_fx.xml"/>
		<patch path="triton_midi.xml"/>
	</data>
	
	<decoders>
		<decoder path="triton_decoder.xml"/>
	</decoders>
	
	<interfaces>
		<interface path="triton_ui.xml"/>
	</interfaces>
	
	<modes>
		<mode id="prog" caption="Program">
			<bank caption="PROG INT-A" min="0" max="127"/>
			<bank caption="PROG INT-B" min="0" max="127"/>
			<bank caption="PROG INT-C" min="0" max="127"/>
			<bank caption="PROG INT-D" min="0" max="127"/>
			<bank caption="PROG INT-E" min="0" max="127"/>
			<bank caption="PROG INT-F" min="0" max="127"/>
			<bank caption="PROG EXT-A" min="0" max="127"/>
			<bank caption="PROG EXT-B" min="0" max="127"/>
			<bank caption="PROG EXT-C" min="0" max="127"/>
			<bank caption="PROG EXT-D" min="0" max="127"/>
			<bank caption="PROG EXT-E" min="0" max="127"/>
			<bank caption="PROG EXT-F" min="0" max="127"/>
			<bank caption="PROG EXT-G" min="0" max="127"/>
			<bank caption="PROG EXT-H" min="0" max="127"/>
		</mode>
		<mode id="combi" caption="Combination">
			<bank caption="COMBI INT-A" min="0" max="127"/>
			<bank caption="COMBI INT-B" min="0" max="127"/>
			<bank caption="COMBI INT-C" min="0" max="127"/>
			<bank caption="COMBI INT-D" min="0" max="127"/>
			<bank caption="COMBI INT-E" min="0" max="127"/>
			<bank caption="COMBI INT-F" min="0" max="127"/>
			<bank caption="COMBI EXT-A" min="0" max="127"/>
			<bank caption="COMBI EXT-B" min="0" max="127"/>
			<bank caption="COMBI EXT-C" min="0" max="127"/>
			<bank caption="COMBI EXT-D" min="0" max="127"/>
			<bank caption="COMBI EXT-E" min="0" max="127"/>
			<bank caption="COMBI EXT-F" min="0" max="127"/>
			<bank caption="COMBI EXT-G" min="0" max="127"/>
			<bank caption="COMBI EXT-H" min="0" max="127"/>
		</mode>
		<mode id="glob" caption="Global">
		</mode>
	</modes>
	
</instrument>

=== romsom/synthed/instruments/kurzweil/k2000/k2000.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	k2000.xml

	This data definition should be compatible with the Kurzweil K2000, 
	K2500 and K2600 series.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE instrument SYSTEM "../../instrument.dtd">

<instrument id="k2000">

	<module id="k2000"/>
	
	<patches>
		<patch path="k2000_pgm.xml"/>
	</patches>
	
	<decoders>
		<decoder path="k2000_decoder.xml"/>
	</decoders>
	
	<interfaces>
		<interface path="k2000_ui.xml"/>
	</interfaces>
	
	<modes>
		<mode id="pgm" caption="Program">
			<bank caption="100" min="0" max="99"/>
			<bank caption="200" min="0" max="99"/>
			<bank caption="300" min="0" max="99"/>
			<bank caption="400" min="0" max="99"/>
			<bank caption="500" min="0" max="99"/>
			<bank caption="600" min="0" max="99"/>
			<bank caption="700" min="0" max="99"/>
			<bank caption="800" min="0" max="99"/>
			<bank caption="900" min="0" max="99"/>
		</mode>
	</modes>
	
</instrument>

=== romsom/synthed/instruments/access/virus_c/virus_c.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	virus_c.xml

	This instrument definition should be compatible with Virus C series.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE instrument SYSTEM "../../instrument.dtd">

<instrument id="virus_c">

	<module id="virus_c"/>
	
	<data>
		<patch path="virus_c_banks.xml"/>
		<patch path="virus_c_midi.xml"/>
	</data>
	
	<decoders>
		<decoder path="virus_decoder.xml"/>
	</decoders>
	
	<interfaces>
		<interface path="virus_c_ui.xml"/>
	</interfaces>
	
	<modes>
		<mode id="single" caption="Singles">
			<bank caption="Singles Bank A" min="0" max="127"/>
			<bank caption="Singles Bank B" min="0" max="127"/>
			<bank caption="Singles Bank C" min="0" max="127"/>
			<bank caption="Singles Bank D" min="0" max="127"/>
			<bank caption="Singles Bank E" min="0" max="127"/>
			<bank caption="Singles Bank F" min="0" max="127"/>
			<bank caption="Singles Bank G" min="0" max="127"/>
			<bank caption="Singles Bank H" min="0" max="127"/>
		</mode>
		<mode id="multi" caption="Multis">
			<bank caption="Multis Bank" min="0" max="127"/>
		</mode>
		<mode id="global" caption="Globals">
		</mode>
	</modes>
	
</instrument>

=== romsom/synthed/instruments/korg/triton/triton.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	triton.xml

	This instrument definition should be compatible with Korg TRITON, pro, 
	and proX. Korg TRITON LE and KARMA differ slightly, so they 
	can be derived from this definition at a later time.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE instrument SYSTEM "../../instrument.dtd">

<instrument id="triton">

	<module id="triton"/>
	
	<patches>
		<patch path="triton_pcm.xml"/>
		<patch path="triton_fx.xml"/>
	</patches>
	
	<decoders>
		<decoder path="triton_decoder.xml"/>
	</decoders>
	
	<interfaces>
		<interface path="triton_ui.xml"/>
	</interfaces>
	
	<modes>
		<mode id="prog" caption="Program">
			<bank caption="PROG A" min="0" max="127"/>
			<bank caption="PROG B" min="0" max="127"/>
			<bank caption="PROG C" min="0" max="127"/>
			<bank caption="PROG D" min="0" max="127"/>
			<bank caption="PROG E" min="0" max="127"/>
			<bank caption="PROG F" min="0" max="127"/>
		</mode>
		<mode id="combi" caption="Combination">
			<bank caption="COMBI A" min="0" max="127"/>
			<bank caption="COMBI B" min="0" max="127"/>
			<bank caption="COMBI C" min="0" max="127"/>
			<bank caption="COMBI D" min="0" max="127"/>
		</mode>
		<mode id="glob" caption="Global">
		</mode>
	</modes>
	
</instrument>

=== romsom/synthed/instruments/synthed/synthdev.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	synthdev.xml

	This instrument definition is used by SynthEd.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE instrument SYSTEM "../instrument.dtd">

<instrument id="synthdev">

	<module id="synthdev"/>
	
	<data>
	</data>
	
	<decoders>
		<decoder path="synthdev_decoder.xml"/>
	</decoders>
	
	<interfaces>
		<interface path="synthdev_ui.xml"/>
	</interfaces>
	
	<modes>
	</modes>
	
</instrument>
