=== romsom/synthed/instruments/interface.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    interface.dtd

    This interface definition schema is designed to describe and 
    facilitate editing of MIDI synthesizer sysex parameters.
    
    Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.
    
    This program is free software; you can redistribute it and/or modify it 
    under the terms of the GNU General Public License as published by the 
    Free Software Foundation; either version 2 of the License, or (at your 
    option) any later version.
    
    This program is distributed in the hope that it will be useful, but 
    WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
    General Public License for more details.
    
    You should have received a copy of the GNU General Public License 
    along with this program; if not, write to the Free Software Foundation, 
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT interface (modes)>
<!ATTLIST interface
    id ID #REQUIRED
    caption CDATA #IMPLIED>

<!ELEMENT modes (mode*)>

<!ELEMENT mode (page+)>
<!ATTLIST mode
    id ID #IMPLIED
    caption CDATA #IMPLIED
    patch CDATA #IMPLIED>
    
<!ELEMENT page (tab+)>
<!ATTLIST page
    id ID #IMPLIED
    caption CDATA #IMPLIED>
    
<!ELEMENT tab (parameter*,group*)>
<!ATTLIST tab
    id ID #IMPLIED
    url CDATA #IMPLIED
    caption CDATA #IMPLIED
    decoder CDATA #IMPLIED
    enable CDATA #IMPLIED
    mode CDATA #IMPLIED
    patch CDATA #IMPLIED
    reset CDATA #IMPLIED>
    
<!ELEMENT group (parameter*,(group|widget)*)>
<!ATTLIST group
    id ID #IMPLIED
    border (none|normal|bold) #IMPLIED
    caption CDATA #IMPLIED
    layout (horizontal|vertical) #IMPLIED
    rows CDATA #IMPLIED
    columns CDATA #IMPLIED
    enable CDATA #IMPLIED>
    
<!ELEMENT widget (parameter)*>
<!ATTLIST widget
    caption CDATA #IMPLIED
    control (button|check|choice|diagram|edit|envelope|gauge|label|radio|slider|space|spin|text) #REQUIRED
    layout (horizontal|vertical) #IMPLIED
    format CDATA #IMPLIED
    decoder CDATA #IMPLIED
    enable CDATA #IMPLIED>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
    id CDATA #REQUIRED
    indexer (true|false) #IMPLIED>

=== romsom/synthed/instruments/access/virus_c/virus_c_ui.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	virus_c_ui.xml

	This user interface definition should be compatible with Virus C.
	
	Copyright (c) 2004 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE interface SYSTEM "../../interface.dtd">

<interface id="virus_c" caption="Virus C">

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Each editable mode is described here.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<modes>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Single mode.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<mode id="single" patch="single" caption="Single">
	<page caption="Main Edit">
		<tab caption="Main" url="virus_c_main.htm"/>
		<tab caption="Inputs" url="virus_c_main_inputs.htm"/>
	</page>
	<page caption="Arpeggiator">
		<tab caption="Arp" url="virus_c_arp.htm"/>
	</page>
	<page caption="LFO/Mod">
		<tab caption="LFO1" url="virus_c_mod_lfo1.htm"/>
		<tab caption="LFO2" url="virus_c_mod_lfo2.htm"/>
		<tab caption="LFO3" url="virus_c_mod_lfo3.htm"/>
		<tab caption="Mod Matrix" url="virus_c_mod_matrix.htm"/>
	</page>
	<page caption="Oscillators">
		<tab caption="Common" url="virus_c_osc_common.htm"/>
		<tab caption="Oscillator 1" url="virus_c_osc1.htm"/>
		<tab caption="Oscillator 2" url="virus_c_osc2.htm"/>
		<tab caption="Oscillator 3" url="virus_c_osc3.htm"/>
	</page>
	<page caption="Filters">
		<tab caption="Common" url="virus_c_filter_common.htm"/>
		<tab caption="Filter 1" url="virus_c_filter1.htm"/>
		<tab caption="Filter 2" url="virus_c_filter2.htm"/>
	</page>
	<page caption="Amplifier">
		<tab caption="Mixer" url="virus_c_amp_mixer.htm"/>
		<tab caption="Envelope" url="virus_c_amp_env.htm"/>
	</page>
	<page caption="Effects">
		<tab caption="Vocoder" url="virus_c_fx_vocoder.htm"/>
		<tab caption="Dist/Chorus/Phaser" url="virus_c_fx_fx.htm"/>
		<tab caption="Delay/Reverb" url="virus_c_fx_delay.htm"/>
		<tab caption="Boost/EQ" url="virus_c_fx_eq.htm"/>
	</page>
</mode>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Todo: multi and global modes
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

</modes>
</interface>

=== romsom/synthed/instruments/korg/triton/triton_ui.xml
<?xml version="1.0"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	triton_ui.xml

	This user interface definition should be compatible with Korg TRITON, pro, 
	proX, Rack and Studio. Korg TRITON LE and KARMA differ slightly, so they 
	can be derived from this definition at a later time.
	
	Copyright (c) 2002 by John Bair. ALL RIGHTS RESERVED.

	This program is free software; you can redistribute it and/or modify it 
	under the terms of the GNU General Public License as published by the 
	Free Software Foundation; either version 2 of the License, or (at your 
	option) any later version.
	
	This program is distributed in the hope that it will be useful, but 
	WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
	General Public License for more details.
	
	You should have received a copy of the GNU General Public License 
	along with this program; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA	
	
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE interface SYSTEM "../../interface.dtd">

<interface id="triton" caption="TRITON">

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Each editable mode is described here.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<modes>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Program mode.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<mode id="pcm" patch="pcm" caption="Program (PCM)">
	<page caption="Play">
		<tab caption="Performance Edit" url="triton_perfedit.htm"/>
		<tab caption="Arpeggiator" url="triton_arp.htm"/>
	</page>
	<page caption="Basic">
	        <tab caption="Program Basic" url="triton_pgmbasic.htm"/>
		<tab caption="OSC Basic" url="triton_oscbasic.htm"/>
		<tab caption="Velocity Zone" url="triton_vzone.htm"/>
		<tab caption="Controllers" url="triton_controllers.htm"/>
	</page>
	<page caption="Pitch">
		<tab caption="OSC1 Pitch Mod." url="triton_osc1pitch.htm"/>
		<tab caption="OSC2 Pitch Mod." url="triton_osc2pitch.htm"/>
		<tab caption="Pitch EG" url="triton_pitcheg.htm"/>
	</page>
	<page caption="Filter">
		<tab caption="Filter 1" url="triton_filter1.htm"/>
		<tab caption="Filter 1 Mod." url="triton_filter1mod.htm"/>
		<tab caption="Filter 1 LFO" url="triton_filter1lfo.htm"/>
		<tab caption="Filter 1 EG" url="triton_filter1eg.htm"/>
		<tab caption="Filter 2" url="triton_filter2.htm"/>
		<tab caption="Filter 2 Mod." url="triton_filter2mod.htm"/>
		<tab caption="Filter 2 LFO" url="triton_filter2lfo.htm"/>
		<tab caption="Filter 2 EG" url="triton_filter2eg.htm"/>
	</page>
	<page caption="Amp">
		<tab caption="Amp 1 Level/Pan" url="triton_amp1.htm"/>
		<tab caption="Amp 1 Mod." url="triton_amp1mod.htm"/>
		<tab caption="Amp 1 EG" url="triton_amp1eg.htm"/>
		<tab caption="Amp 2 Level/Pan" url="triton_amp2.htm"/>
		<tab caption="Amp 2 Mod." url="triton_amp2mod.htm"/>
		<tab caption="Amp 2 EG" url="triton_amp2eg.htm"/>
	</page>
	<page caption="Common LFO">
		<tab caption="OSC1 LFO1" url="triton_osc1lfo1.htm"/>
		<tab caption="OSC1 LFO2" url="triton_osc1lfo2.htm"/>
		<tab caption="OSC2 LFO1" url="triton_osc2lfo1.htm"/>
		<tab caption="OSC2 LFO2" url="triton_osc2lfo2.htm"/>
	</page>
	<page caption="Arpeggiator">
		<tab caption="Setup" url="triton_arpsetup.htm"/>
		<tab caption="Zone" url="triton_arpzone.htm"/>
	</page>
	<page caption="Insert Effect">
		<tab caption="Routing" url="triton_routing.htm"/>
		<tab caption="Insert FX" url="triton_insertfx.htm"/>
		<!-- The mode attribute in the following tabs indicates dynamic content.-->
		<tab caption="IFX 1" mode="fx" decoder="scale_fx_tabs" reset="true">
			<parameter id="IFX1_data_offset"/>
			<parameter id="IFX1_effect_no"/>
		</tab>
		<tab caption="IFX 2" mode="fx" decoder="scale_fx_tabs" reset="true">
			<parameter id="IFX2_data_offset"/>
			<parameter id="IFX2_effect_no"/>
		</tab>
		<tab caption="IFX 3" mode="fx" decoder="scale_fx_tabs" reset="true">
			<parameter id="IFX3_data_offset"/>
			<parameter id="IFX3_effect_no"/>
		</tab>
		<tab caption="IFX 4" mode="fx" decoder="scale_fx_tabs" reset="true">
			<parameter id="IFX4_data_offset"/>
			<parameter id="IFX4_effect_no"/>
		</tab>
		<tab caption="IFX 5" mode="fx" decoder="scale_fx_tabs" reset="true">
			<parameter id="IFX5_data_offset"/>
			<parameter id="IFX5_effect_no"/>
		</tab>
	</page>
</mode>

<mode id="fx" caption="Effects">
	<page caption="Effects Editors">
		<tab patch="fx_000" caption="No Effect" url="triton_fx000.htm"/>
		<tab patch="fx_001" caption="St.Amp Simulation" url="triton_fx001.htm"/>
		<tab patch="fx_002" caption="Stereo Compressor" url="triton_fx002.htm"/>
		<tab patch="fx_003" caption="Stereo Limiter" url="triton_fx003.htm"/>
		<tab patch="fx_004" caption="Multiband Limiter" url="triton_fx004.htm"/>
		<tab patch="fx_005" caption="Stereo Gate" url="triton_fx005.htm"/>
		<tab patch="fx_006" caption="OD/Hi.Gain Wah" url="triton_fx006.htm"/>
		<tab patch="fx_007" caption="St. Parametric 4EQ" url="triton_fx007.htm"/>
		<tab patch="fx_008" caption="St. Graphic 7EQ" url="triton_fx008.htm"/>
		<tab patch="fx_009" caption="St. Wah/Auto Wah" url="triton_fx009.htm"/>
		<tab patch="fx_010" caption="St. Random Filter" url="triton_fx010.htm"/>
	</page>
</mode>

</modes>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Todo: GLOBAL, COMBI, MULTI and SAMPLING modes
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</interface>

=== romsom/synthed/instruments/synthed/synthdev_ui.xml
<!DOCTYPE interface SYSTEM "../interface.dtd">

<interface id="synthed" caption="SynthEd">

<modes>
    <mode id="edit_instrument">
        <page>
            <tab id="instrument">
                <group caption="instrument" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                    <widget caption="caption" control="edit" />
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_list">
        <page>
            <tab id="list">
                <group caption="list" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
            
    <mode id="edit_item">
        <page>
            <tab id="item">
                <group caption="item" layout="vertical" columns="2">
                    <widget caption="value" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
           
    <mode id="edit_scale">
        <page>
            <tab id="scale">	
                <group caption="scale" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                    <widget caption="format" control="edit"/>
                    <widget caption="unit" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_range">
        <page>
            <tab id="range">
                <group caption="range" layout="vertical" columns="2">
                    <widget caption="mindata" control="edit"/>
                    <widget caption="maxdata" control="edit"/>
                    <widget caption="minval" control="edit"/>
                    <widget caption="increment" control="edit"/>
                    <widget caption="format" control="edit"/>
                    <widget caption="unit" control="edit"/>
                    <widget caption="multiplier" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_mode">
        <page>
            <tab id="mode">	
                <group caption="mode" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                    <widget caption="caption" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_page">
        <page>
            <tab id="page">
                <group caption="page" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                    <widget caption="caption" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
        
    <mode id="edit_tab">
        <page>
            <tab id="tab">
                <group caption="tab" layout="vertical" columns="2">
                    <widget caption="id" control="edit"/>
                    <widget caption="caption" control="edit"/>
                    <widget caption="enable" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
        
    <mode id="edit_group">
        <page>
            <tab id="group">
                <group caption="group" layout="vertical" columns="2">
                    <widget caption="caption" control="edit"/>
                    <widget caption="layout" control="choice" decoder="list" reference="list_layout"/>
                    <widget caption="rows" control="spin"/>
                    <widget caption="columns" control="spin"/>
                    <widget caption="enable" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
        
    <mode id="edit_widget">
        <page>
            <tab id="widget">
                <group caption="widget" layout="vertical" columns="2">
                    <widget caption="caption" control="edit"/>
                    <widget caption="control" control="choice"/>
                    <widget caption="layout" control="choice" decoder="list" reference="list_layout"/>
                    <widget caption="format" control="edit"/>
                    <widget caption="decoder" control="choice" decoder="list" reference="list_decoder"/>
                    <widget caption="reference" control="choice" decoder="list" reference="list_ids"/>
                    <widget caption="enable" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_parameter">
        <page>
            <tab id="value">
                <group caption="value" layout="vertical" columns="2">
                    <widget caption="display" control="edit"/>
                    <widget caption="indexer" control="edit"/>
                    <widget caption="min" control="edit"/>
                    <widget caption="max" control="edit"/>
                    <widget caption="type" control="edit"/>
                    <widget caption="pad" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_byte">
        <page>
            <tab id="byte">
                <group caption="byte" layout="vertical" columns="2">
                    <widget caption="offset" control="edit"/>
                    <widget caption="bitstart" control="edit"/>
                    <widget caption="bitstop" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
    
    <mode id="edit_array">
        <page>
            <tab id="array">
                <group caption="array" layout="vertical" columns="2">
                    <widget caption="offset" control="edit"/>
                    <widget caption="length" control="edit"/>
                </group>
            </tab>
        </page>
    </mode>
        
</modes>

</interface>
